import { eight } from "./pdf_exercises/eight";
import { eleven } from "./pdf_exercises/eleven";
import { five } from "./pdf_exercises/five";
import { four } from "./pdf_exercises/four";
import { fourteen } from "./pdf_exercises/fourteen";
import { nine } from "./pdf_exercises/nine";
import { one } from "./pdf_exercises/one";
import { seven } from "./pdf_exercises/seven";
import { six } from "./pdf_exercises/six";
import { ten } from "./pdf_exercises/ten";
import { thirteen } from "./pdf_exercises/thirteen";
import { twelve } from "./pdf_exercises/twelve";
import { two_three } from "./pdf_exercises/two_three";

one();
two_three();
four();
five();
six();
seven();
eight();
nine();
ten();
eleven();
twelve();
thirteen();
fourteen();